blueprint:
  name: Motion-activated Switch and or switch with Elevation + check on light
  domain: automation
  source_url: https://community.home-assistant.io/t/motion-activate-switch-or-switch-based-on-dayswitch-sun-elevation/265010
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: false
    switch_target:
      name: Switch
      selector:
        target:
          entity:
            domain: switch
    no_motion_wait:
      name: Wait time
      description: Time to leave the switch on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    below_elevation:
      name: Below sun elevation
      description: Solar elevation. This is the angle between the sun and the horizon.
        Negative values mean the sun is below the horizon.
      default: 1
      selector:
        number:
          min: -90.0
          max: 90.0
          unit_of_measurement: degrees
          step: 1.0
          mode: slider
    light_target:
      name: Light
      description: Don't do anything if this light is on.
      selector:
        target:
          entity:
            domain: light
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input motion_entity
  from: 'off'
  to: 'on'
variables:
  below_elevation: !input below_elevation
  light_target: !input light_target
condition:
  - condition: template
    value_template: >
      {{ state_attr('sun.sun','elevation') <= (below_elevation | float) }}
  - condition: template
    value_template: >
      {{ not is_state(light_target.entity_id, 'on') }}
action:
  - service: switch.turn_on
    target: !input switch_target
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - choose:
      - conditions:
          - condition: state
            entity_id: !input light_target
            state: 'off'
        sequence:
          - service: switch.turn_off
            target: !input switch_target
